version: "3"
services:
  app:
    build:
      context: .
    ports:
      - "3000:3000"
    depends_on:
      - db
  db:
    image: postgres:latest
    environment:
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=18f18010 
      - POSTGRES_DB=booking_BD 

  api:
  build: 
  context:
  dockerfile: Dockerfile 
  ports:
  - 3000:3000
  environment:
    - DATABASE_USER= postgres
    - DATABASE_NAME= booking_BD
    - DATABASE_PASSWORD=SE7Tl6r6KeLxpDjGHgxbDwYRGnXmpRZo
    - DATABASE_HOST= localhost
    - DATABASE_PORT=5432
  