version: "3"
services:
 postgres: 
  image: postgres:12-alpine
  #to spacifiy some enviroment keyworld 
  environment:
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=18f18010 
      - POSTGRES_DB=booking_BD 
      #This all the API servers for go-crud 
 api:
#Should build all the images from 
  build:
#Specifiy the context to specify the image, the dot means the current postgres folder    
   context: .
  #Docker file keyworld to tell the docker compose where to find the docker file and build the image 
   dockerfile: Dockerfile 
  #Next, we should spacify the port which will publish port 3000 to the host machien, to call go-crud API from outside of the container 
  ports:
     - "3000:3000"
  enviroment:
      - DB_URL=postgresql://postgres:18f18010@postgres:5432/booking_BD?sslmode=disable  
api: 
     build: 
      context:
      dockerfile: Dockerfile 
      ports:
      - 3000:3000
     environment:
     - DATABASE_USER= postgres
     - DATABASE_NAME= booking_BD
     - DATABASE_PASSWORD=SE7Tl6r6KeLxpDjGHgxbDwYRGnXmpRZo
     - DATABASE_HOST= localhost
     - DATABASE_PORT=5432
