version: "3.9"
services: 
  postgres: 
    image: postgres:12-alpine
    environment:
      #All API services  
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=18f18010
      - POSTGRES_DB=booking_DB
  api:
    build: 
      context: .
      dockerfile: Dockerfile 
        #To specifiy the port which will publish the port in the host machine, to call the go-crud API from outside the container.
    ports: 
      - "5000:3000" 
    environment: 
      - DB_URL=postgresql://postgres:18f18010@postgres:5432/booking_DB?sslmode=disable


