version: "3"
services:
  postgres: 
    image: postgres:12-alpine 
   
    environment:
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=18f18010
      - POSTGRES_DB=booking_BD

    api:
    build: 
    context: .
    dockerfile: Dockerfile 
    ports:
      -"3000:3000" 
  environment:
      - DB_URL=postgres://postgres:18f18010@localhost:5432/booking_BD? sslmode=disable 

    
    

  



 


  