version: "3"
services:
  app:
    build:
      context: .
    ports:
      - "3000:3000"
    depends_on:
      - db
  db:
    image: postgres:latest
    environment:
      - POSTGRES_USER=your_username
      - POSTGRES_PASSWORD=your_password
      - POSTGRES_DB=your_database_name

  api:
  build: 
  context:
  dockerfile: Dockerfile 
  ports:
  - 3000:3000
  environment:
    - DATABASE_NAME=aziiuqrt
    - DATABASE_PASSWORD=SE7Tl6r6KeLxpDjGHgxbDwYRGnXmpRZo
    - DATABASE_HOST= localhost
    - DATABASE_PORT=5432


  